steps:
  - name: 'gcr.io/cloud-builders/go'
    args:
    - 'install'
    - 'hello'
    env:
    - 'PROJECT_ROOT=hello'

  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA-$BUILD_ID'
    - '.'

  - name: 'joonathan/alpine-envsubst'
    args:
    - '.kubernetes/deployment.yaml'
    env:
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'PROJECT_ID=$PROJECT_ID'
    - 'REPO_NAME=$REPO_NAME'
    - 'BUILD_ID=$BUILD_ID'

  - name: 'joonathan/alpine-envsubst'
    args:
    - '.kubernetes/service.yaml'
    env:
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'PROJECT_ID=$PROJECT_ID'
    - 'REPO_NAME=$REPO_NAME'
    - 'BUILD_ID=$BUILD_ID'

  - name: 'joonathan/alpine-envsubst'
    args:
    - '.kubernetes/ingress.yaml'
    env:
    - 'REPO_NAME=$REPO_NAME'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'apply'
    - '-f'
    - '.kubernetes/deployment.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=demo'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'apply'
    - '-f'
    - '.kubernetes/service.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=demo'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'apply'
    - '-f'
    - '.kubernetes/ingress.yaml'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=demo'

images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
